title: Anirudh Oppiliappan
url: "https://anirudh.fi/"
description: ""
author:
  name: "Anirudh Oppiliappan"
  email: "anirudh@oppiliappan.com"
defaultTemplate: text.html
preBuild:
  - tailwindcss -i input.css -o static/styles/tw.css
